[package]
name = "lab3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cg_library = { path = "../cg_library" }
ordered-float = "2.0"
num-traits = "0.2.15"
